runtime: go112

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(favicon\.ico|index\.html|logo192\.png|logo512\.png|manifest\.json|robots\.txt)$
  static_files: build/\1
  upload: build/(favicon\.ico|index\.html|logo192\.png|logo512\.png|manifest\.json|robots\.txt)
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: build/static
  secure: always
  redirect_http_response_code: 301
