runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
